### ISSUE TITLE
cp_demo not compiling

### ISSUE THREAD

**Issue by MartinAbilev** [Jack-Ji/jok#12]
src\main.zig:7:14: error: type '@TypeOf(null)' does not support field access
var world: cp.World = undefined;

me new to zig so maybe something not get here

**Comment by Jack-Ji** [comment]
It compiles and runs well on my machine. Are you using latest zig compiler?

**Comment by MartinAbilev** [comment]
i use zig-windows-x86_64-0.14.0-dev.125+a016ca617

**Comment by MartinAbilev** [comment]
ok i found problem is when i copy sp demo in my clean project it not  compile but i found from this repo it works so probably i miss something in my build.zig

**Comment by Jack-Ji** [comment]
Maybe the link option is missing? `chipmunk` isn't linked ny default, please see last parameter of `jok.createGame`.

**Comment by MartinAbilev** [comment]
yup thats the reason thanks :)
