### ISSUE TITLE
cp dynamic position not changes on update

### ISSUE THREAD

**Issue by MartinAbilev** [Jack-Ji/jok#13]
so i created just one dynamic object globaly 

```
 const   dynamic_body: cp.World.ObjectOption.BodyProperty = .{
            .dynamic = .{
                .position = .{
                    .x = 0,
                    .y = 0,
                },
            },
        };
```

add to world in init

```
        _= try world.addObject(.{
            .body = dynamic_body,
            .shapes = &.{
                .{
                    .circle = .{
                        .radius = 15,
                        .physics = .{
                                    .weight = .{ .mass = 1 },
                                    .elasticity = 0.5,
                                },
                    },
                },
            },
        });
```

then on update try to read its position, but on every step value is the  same :(
where on screen object falls down all work as expected...

```
pub fn update(ctx: jok.Context) !void {
    // _ = ctx;
        world.update(ctx.deltaSeconds()) 
        const px: i32 = @intFromFloat(dynamic_body.dynamic.position.x);
        const py: i32 = @intFromFloat(dynamic_body.dynamic.position.y);
        print("bug {} x, y: {}, {}\n", .{0, px, py});
}
```

do i mising something agen ?

**Comment by Jack-Ji** [comment]
You need to update the physical status within `chipmunk`, by calling     `world.update(ctx.deltaSeconds());`. I recommend reading `chipmunk`'s official document, its very well written.

**Comment by Jack-Ji** [comment]
OK, I think your real problem is from reusing `dynamic_body`, which is only for initialization. In order to get updated position, you should use index returned by `world.addObject` to access array `world.objects`, which contains `cpBody/cpShape`. `jok` only get you this far, you need to use c api of chipmunk to get further information, such as position/rotation etc.

**Comment by MartinAbilev** [comment]
i try kinda

```
        const b =   world.objects.items[0].body;
        const bv = cp.cpBodyGetPosition(b);

        print("b {}\n", .{bv});
```

error: root struct of file 'deps.chipmunk.chipmunk' has no member named 'cpBodyGetPosition'
        const bv = cp.cpBodyGetPosition(b);
        
        so no much chips api can help me here

**Comment by Jack-Ji** [comment]
Try `cp.c.cpBodyGetPosition`.
One more thing, `world.objects.items[0].body` is optional type, you might consider using `.?` operator to get real pointer.

It seems you are not familiar with basic zig knowledge well enough, I recommend you to read official documentation on ziglang.org more thoroughly. Its required to be able to dig into official document and source code when working with foss project, especially if you choose to use a programming language still being developed like zig.

**Comment by MartinAbilev** [comment]
yuhuu thanks  it works now :)   yes i just started with zig so sometimes get stuck.

```
        const b =   world.objects.items[0].body.?;
        const bv = cp.c.cpBodyGetPosition(b);

        print("b {}\n", .{bv});
```


b deps.chipmunk.c.struct_cpVect{ .x = 0e0, .y = 1.0546666e3 }
b deps.chipmunk.c.struct_cpVect{ .x = 0e0, .y = 1.0735e3 }
b deps.chipmunk.c.struct_cpVect{ .x = 0e0, .y = 1.0925e3 }
b deps.chipmunk.c.struct_cpVect{ .x = 0e0, .y = 1.1116666e3 }
b deps.chipmunk.c.struct_cpVect{ .x = 0e0, .y = 1.131e3 }
b deps.chipmunk.c.struct_cpVect{ .x = 0e0, .y = 1.1505e3 }.....
