### ISSUE TITLE
Quick wins for hacktoberfest

### ISSUE THREAD

**Issue by lenniezelk** [Jack-Ji/jok#21]
I am interested in contributing to the project. Is it possible to create some issues with quick win tags? I think would be a great way to ease people into the project.

**Comment by Jack-Ji** [comment]
Sure, just tell me what I need to do.

**Comment by lenniezelk** [comment]
Chores or small tasks like easy bug fixes or small improvements are good candidates for quick wins. Also adding to examples is a good candidate I think which is what I am thinking of doing.

**Comment by Jack-Ji** [comment]
ok, I think I get your point. Will think of some `contributor friendly` issue later.

**Comment by Jack-Ji** [comment]
I created several `good first issue`, most of which should be fun to implement, feel free to contribute.
