### ISSUE TITLE
error: redefinition of typedef 'MIDIEventList' is a C11 feature while compiling miniaudio.h on Mac

### ISSUE THREAD

**Issue by tsoumdoa** [Jack-Ji/jok#37]
I wanted to try out jok and run into the following compile error.. 

I'm using the nominated zig version (v0.14.0-dev.1911+3bf89f55c) on M4 MBP. 

Judged by the message below, I'm assuming it's something to do with a Mac OS native layer (Audio ToolBox)  and the complier feature (redefinition of typedef 'MIDIEventList' is a C11 feature) ...? 

With my limited knowledge, I can't imagine how to fix this without changing the source code of miniaudio itself? So, it would be great if someone can come up with a solution for this...

Thank you so much in advance!

The error message when I run a command to build an example:  
> ❯ zig build hello
hello
└─ run hello
   └─ zig build-exe hello Debug native
      └─ zig build-lib jok Debug native
         └─ zig build-lib miniaudio Debug native 20 errors
/Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/System/Library/Frameworks/AudioToolbox.framework/Headers/MusicDevice.h:178:30: error: redefinition of typedef 'MIDIEventList' is a C11 feature
typedef struct MIDIEventList MIDIEventList;
                             ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:31812:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:31812:
#include <AudioToolbox/AudioToolbox.h>
         ^
/Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:19:10: note: in file included from /Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:19:
#include <AudioToolbox/AUGraph.h>
         ^
/Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/System/Library/Frameworks/AudioToolbox.framework/Headers/AUGraph.h:30:10: note: in file included from /Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/System/Library/Frameworks/AudioToolbox.framework/Headers/AUGraph.h:30:
#include <AudioToolbox/AudioUnit.h>
         ^
/Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioUnit.h:23:10: note: in file included from /Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioUnit.h:23:
#include <AudioToolbox/MusicDevice.h>
         ^
/Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioUnitProperties.h:1367:30: note: previous definition is here
typedef struct MIDIEventList MIDIEventList;
                             ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91489:30: error: always_inline function 'vmovq_n_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        ma_dr_mp3_f4 scale = MA_DR_MP3_VSET(32768.0f);
                             ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:89949:24: note: expanded from macro 'MA_DR_MP3_VSET'
#define MA_DR_MP3_VSET vmovq_n_f32
                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91490:26: error: always_inline function 'vmulq_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        ma_dr_mp3_f4 a = MA_DR_MP3_VMUL(MA_DR_MP3_VLD(&in[i  ]), scale);
                         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:89952:24: note: expanded from macro 'MA_DR_MP3_VMUL'
#define MA_DR_MP3_VMUL vmulq_f32
                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91491:26: error: always_inline function 'vmulq_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        ma_dr_mp3_f4 b = MA_DR_MP3_VMUL(MA_DR_MP3_VLD(&in[i+4]), scale);
                         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:89952:24: note: expanded from macro 'MA_DR_MP3_VMUL'
#define MA_DR_MP3_VMUL vmulq_f32
                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91507:31: error: always_inline function 'vmovq_n_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        a = MA_DR_MP3_VADD(a, MA_DR_MP3_VSET(0.5f));
                              ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:89949:24: note: expanded from macro 'MA_DR_MP3_VSET'
#define MA_DR_MP3_VSET vmovq_n_f32
                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91507:13: error: always_inline function 'vaddq_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        a = MA_DR_MP3_VADD(a, MA_DR_MP3_VSET(0.5f));
            ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:89950:24: note: expanded from macro 'MA_DR_MP3_VADD'
#define MA_DR_MP3_VADD vaddq_f32
                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91508:31: error: always_inline function 'vmovq_n_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        b = MA_DR_MP3_VADD(b, MA_DR_MP3_VSET(0.5f));
                              ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:89949:24: note: expanded from macro 'MA_DR_MP3_VSET'
#define MA_DR_MP3_VSET vmovq_n_f32
                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91508:13: error: always_inline function 'vaddq_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        b = MA_DR_MP3_VADD(b, MA_DR_MP3_VSET(0.5f));
            ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:89950:24: note: expanded from macro 'MA_DR_MP3_VADD'
#define MA_DR_MP3_VADD vaddq_f32
                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91509:38: error: always_inline function 'vcvtq_s32_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcma = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(a), vreinterpretq_s32_u32(vcltq_f32(a, MA_DR_MP3_VSET(0)))));
                                     ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91509:91: error: always_inline function 'vmovq_n_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcma = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(a), vreinterpretq_s32_u32(vcltq_f32(a, MA_DR_MP3_VSET(0)))));
                                                                                          ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:89949:24: note: expanded from macro 'MA_DR_MP3_VSET'
#define MA_DR_MP3_VSET vmovq_n_f32
                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91509:78: error: always_inline function 'vcltq_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcma = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(a), vreinterpretq_s32_u32(vcltq_f32(a, MA_DR_MP3_VSET(0)))));
                                                                             ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91509:56: error: always_inline function 'vreinterpretq_s32_u32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcma = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(a), vreinterpretq_s32_u32(vcltq_f32(a, MA_DR_MP3_VSET(0)))));
                                                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91509:27: error: always_inline function 'vqaddq_s32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcma = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(a), vreinterpretq_s32_u32(vcltq_f32(a, MA_DR_MP3_VSET(0)))));
                          ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91509:16: error: always_inline function 'vqmovn_s32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcma = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(a), vreinterpretq_s32_u32(vcltq_f32(a, MA_DR_MP3_VSET(0)))));
               ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91510:38: error: always_inline function 'vcvtq_s32_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcmb = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(b), vreinterpretq_s32_u32(vcltq_f32(b, MA_DR_MP3_VSET(0)))));
                                     ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91510:91: error: always_inline function 'vmovq_n_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcmb = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(b), vreinterpretq_s32_u32(vcltq_f32(b, MA_DR_MP3_VSET(0)))));
                                                                                          ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:89949:24: note: expanded from macro 'MA_DR_MP3_VSET'
#define MA_DR_MP3_VSET vmovq_n_f32
                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91510:78: error: always_inline function 'vcltq_f32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcmb = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(b), vreinterpretq_s32_u32(vcltq_f32(b, MA_DR_MP3_VSET(0)))));
                                                                             ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91510:56: error: always_inline function 'vreinterpretq_s32_u32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcmb = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(b), vreinterpretq_s32_u32(vcltq_f32(b, MA_DR_MP3_VSET(0)))));
                                                       ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91510:27: error: always_inline function 'vqaddq_s32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcmb = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(b), vreinterpretq_s32_u32(vcltq_f32(b, MA_DR_MP3_VSET(0)))));
                          ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.h:91510:16: error: always_inline function 'vqmovn_s32' requires target feature 'aes', but would be inlined into function 'ma_dr_mp3dec_f32_to_s16' that is compiled without support for 'aes'
        pcmb = vqmovn_s32(vqaddq_s32(vcvtq_s32_f32(b), vreinterpretq_s32_u32(vcltq_f32(b, MA_DR_MP3_VSET(0)))));
               ^
/Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:10: note: in file included from /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c:2:
#include "miniaudio.h"
         ^
error: the following command failed with 20 compilation errors:
/Users/<usr>/.zvm/nominated/zig build-lib -cflags -std=c99 -- /Users/<usr>/repo/@sandbox/jok/deps/zaudio/src/zaudio.c -cflags -DMA_NO_WEBAUDIO -DMA_NO_ENCODING -DMA_NO_NULL -DMA_NO_JACK -DMA_NO_DSOUND -DMA_NO_WINMM -std=c99 -fno-sanitize=undefined -DMA_NO_RUNTIME_LINKING -- /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio/miniaudio.c -ODebug -I /Users/<usr>/repo/@sandbox/jok/deps/zaudio/libs/miniaudio -F /Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/System/Library/Frameworks -isystem /Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/usr/include -L /Users/<usr>/.cache/zig/p/122047a9298c4c9dd43389d418d6826d469b192246ba0944102964cdc57f94c562df/macos12/usr/lib -Mroot -framework CoreAudio -framework CoreFoundation -framework AudioUnit -framework AudioToolbox -lc --cache-dir /Users/<usr>/repo/@sandbox/jok/.zig-cache --global-cache-dir /Users/<usr>/.cache/zig --name miniaudio -static --zig-lib-dir /Users/<usr>/.zvm/nominated/lib/ --listen=-
Build Summary: 13/19 steps succeeded; 1 failed
hello transitive failure
└─ run hello transitive failure
   ├─ zig build-exe hello Debug native transitive failure
   │  └─ zig build-lib jok Debug native transitive failure
   │     └─ zig build-lib miniaudio Debug native 20 errors
   └─ install hello transitive failure
      └─ zig build-exe hello Debug native (+10 more reused dependencies)
error: the following build command failed with exit code 1:
/Users/<usr>/repo/@sandbox/jok/.zig-cache/o/58c04bd4a88085e712316d8fdd42d585/build /Users/<usr>/.zvm/nominated/zig /Users/<usr>/.zvm/nominated/lib /Users/<usr>/repo/@sandbox/jok /Users/<usr>/repo/@sandbox/jok/.zig-cache /Users/<usr>/.cache/zig --seed 0xe3d820eb -Z53c210173c95564c hello

**Comment by Jack-Ji** [comment]
Yeah, it's actually a known problem of zaudio. Unfortunately, I dont own a macos machine to debug the problem properly. You can try `no_audio` build option to leave out audio support. Or, do some serious debug yourself, e.g. add `-std=C11` to miniaudio's  build instruction, I doubt it would be that easy however.

**Comment by tsoumdoa** [comment]
Great suggestion, thank you!  I managed to compile by disabling the audio in the default build options as following. 

I just wanna play with graphics,  so I'll just use this workaround for now! Hope this would help with anyone looking to play with jok on mac... 

In `build.zig`
```diff zig
pub const BuildOptions = struct {
    dep_name: ?[]const u8 = "jok",
+  no_audio: bool = true,
-  no_audio: bool = false,
    use_cp: bool = false,
    use_nfd: bool = false,
    use_ztracy: bool = false,
    enable_ztracy: bool = false,
};
```
