### ISSUE TITLE
Error compiling examples

### ISSUE THREAD

**Issue by noncom** [Jack-Ji/jok#7]
Hi! I'm trying to compile the examples, but I'm getting:

```powershell
PS D:\programming\__zig\jok> zig build hello
zig build-exe hello Debug native: error: error(compilation): clang failed with stderr: D:\programming\__zig\jok\src\deps\audio\c\sdl_impl.c:594:18: error: call to undeclared function 'ma_context_init__sdl'; ISO 
C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```

The SDL version I've setup is `SDL2-devel-2.28.5-mingw`

**Comment by Jack-Ji** [comment]
Hi, what’s your zig’s version?

**Comment by Jack-Ji** [comment]
Fixed by #f26c9

**Comment by noncom** [comment]
> Hi, what’s your zig’s version?

Ahh, sorry, it was `zig-windows-x86_64-0.12.0-dev.1637+673a1efa2/zig`.

But you've already fixed everything, so I'm just mentioning this here for the sake of completeness.
The examples now build and work great for me.

Thank you a lot!
